#!/usr/bin/env python3
# encoding: UTF-8

__doc__ = """
This module was generated by turberfield.ops.svgforger:

fontforge /home/boss/src/turberfield-ops/turberfield/ops/svgforger.py --name=addisonarches \
--prefix=diorama --output=~/src/addisonarches/addisonarches/web/static \
/home/boss/src/addisonarches/assets/formb107.svg \
/home/boss/src/addisonarches/assets/keys.svg \
/home/boss/src/addisonarches/assets/prisoner.svg \
/home/boss/src/addisonarches/assets/prisonofficer.svg \
/home/boss/src/addisonarches/assets/prisonvisitor.svg

"""

from collections import namedtuple
from turberfield.utils.assembly import Assembly

Icon = namedtuple("Icon", ["font", "prefix", "name", "ordinal"])

icons = [
    Icon("addisonarches", "diorama", "formb107", 350),
    Icon("addisonarches", "diorama", "keys", 351),
    Icon("addisonarches", "diorama", "prisoner", 352),
    Icon("addisonarches", "diorama", "prisonofficer", 353),
    Icon("addisonarches", "diorama", "prisonvisitor", 354),
]

Assembly.register(Icon)

