#!/usr/bin/env python3
# encoding: UTF-8

__doc__ = """
This module was generated by turberfield.ops.svgforger:

fontforge turberfield/ops/svgforger.py --name=addisonarches --prefix=diorama \
--output=~/src/addisonarches/addisonarches/web/static \
/home/boss/src/addisonarches/assets/prisonofficer.svg

"""

from collections import namedtuple
from turberfield.utils.assembly import Assembly

Icon = namedtuple("Icon", ["font", "prefix", "name", "ordinal"])

icons = [
    Icon("addisonarches", "diorama", "prisonofficer", 350),
]

Assembly.register(Icon)

